# Generated by Django 4.2.30 on 2026-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_480',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_master',
            field=models.FileField(blank=True, null=True, upload_to='hls/'),
        ),
        migrations.AddField(
            model_name='video',
            name='sprite_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='sprites/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
