# Generated by Django 4.2.30 on 2026-06-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_options_remove_video_video_480_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bitrate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='gif_preview',
            field=models.FileField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('transcoding_1080p', 'Transcoding 1080p'), ('transcoding_720p', 'Transcoding 720p'), ('generating_gif', 'Generating Preview'), ('generating_assets', 'Generating Assets'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
