# Generated by Django 4.2.30 on 2026-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_bitrate_video_codec_video_fps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='gif_preview',
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('transcoding_1080p', 'Transcoding 1080p'), ('transcoding_720p', 'Transcoding 720p'), ('generating_assets', 'Generating Assets'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
